###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/64bb63454b138de04d6d6095

###
DELETE http://localhost:3001/api/persons/64bdb9323fde03291363607b

###
DELETE http://localhost:3001/api/persons/5

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Dead Trump",
  "number": "44444444"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "44444444"
}

###
GET https://phonebook4fullstack.fly.dev/api/persons